% To build the vignette:
% 1. run Sweave("Ryacas-Sym-raw") to create Ryacas-Sym-raw.tex
% 2. build as usual using Rcmd build Ryacas
%
% To build vignette manually:
% 1. Sweave("Ryacas-Sym-raw") to create Ryacas-raw.tex
% 2. Sweave("Ryacas-Sym.Rnw")
% 3. pdflatex Ryacas-Sym.tex


\SweaveOpts{engine=R,eps=FALSE}

%\VignetteIndexEntry{Introduction to Ryacas - Sym Version}
%\VignettePackage{Ryacas}
%\VignetteDepends{XML}


\input{Ryacas-Sym-raw}
