// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// yacas_evaluate
std::vector<std::string> yacas_evaluate(std::string expr);
RcppExport SEXP Ryacas_yacas_evaluate(SEXP exprSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type expr(exprSEXP);
    __result = Rcpp::wrap(yacas_evaluate(expr));
    return __result;
END_RCPP
}
