// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// yacas_init_force_path
void yacas_init_force_path(std::string path, bool ryacas_init);
RcppExport SEXP _Ryacas_yacas_init_force_path(SEXP pathSEXP, SEXP ryacas_initSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type ryacas_init(ryacas_initSEXP);
    yacas_init_force_path(path, ryacas_init);
    return R_NilValue;
END_RCPP
}
// yacas_init_force
void yacas_init_force(bool ryacas_init);
RcppExport SEXP _Ryacas_yacas_init_force(SEXP ryacas_initSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type ryacas_init(ryacas_initSEXP);
    yacas_init_force(ryacas_init);
    return R_NilValue;
END_RCPP
}
// yac_core
std::vector<std::string> yac_core(std::string expr);
RcppExport SEXP _Ryacas_yac_core(SEXP exprSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type expr(exprSEXP);
    rcpp_result_gen = Rcpp::wrap(yac_core(expr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Ryacas_yacas_init_force_path", (DL_FUNC) &_Ryacas_yacas_init_force_path, 2},
    {"_Ryacas_yacas_init_force", (DL_FUNC) &_Ryacas_yacas_init_force, 1},
    {"_Ryacas_yac_core", (DL_FUNC) &_Ryacas_yac_core, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Ryacas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
