# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

yacas_init_force_path <- function(path, ryacas_init = TRUE) {
    invisible(.Call(`_Ryacas_yacas_init_force_path`, path, ryacas_init))
}

yacas_init_force <- function(ryacas_init = TRUE) {
    invisible(.Call(`_Ryacas_yacas_init_force`, ryacas_init))
}

yac_core <- function(expr) {
    .Call(`_Ryacas_yac_core`, expr)
}

